main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_todo/", views.add_todo, name="add_todo"),
    path("delete_todo/<int:todo_id>/", views.delete_todo, name="delete_todo"),
]

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    added_date = models.DateTimeField()
    text = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.text

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from .models import Todo

# Create your views here.
def index(request):
    todo_items = Todo.objects.all().order_by("-added_date")
    return render(request, "main/index.html", {"todo_items": todo_items})


def add_todo(request):
    added_date = timezone.now()
    content = request.POST["content"]
    created_obj = Todo.objects.create(added_date=added_date, text=content)
    length_of_todos = Todo.objects.all().count()

    return HttpResponseRedirect(
        reverse(
            "main:index",
        )
    )


def delete_todo(request, todo_id):
    Todo.objects.get(id=todo_id).delete()

    return HttpResponseRedirect(
        reverse(
            "main:index",
        )
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">To Do App</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

templates/main/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-4">
    <div class="col">
        <form class="row g-3" action="{% url 'main:add_todo' %}" method="POST">
            {% csrf_token %}
            <div class="col-auto">
                <input type="text" class="form-control mb-2 mr-sm-2" name="content" placeholder="type here...">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-2">Submit</button>
            </div>
        </form>
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <ul class="list-group">
            {% for todo_item in todo_items %}
            <li class="list-group-item d-flex justify-content-between" width="50%">
                {{ todo_item.text }}
                <form action="{% url 'main:delete_todo' todo_item.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}